### ISSUE TITLE
Issues with LuaEvents libraries

### ISSUE THREAD

**Issue by StanzillaManticore** [standardcombo/LootMMO#3]
The project includes two, 

https://github.com/standardcombo/LootMMO/blob/main/Data/Scripts/_LuaEvents.lua
https://github.com/standardcombo/LootMMO/blob/main/Data/Scripts/_LuaEvents_1.lua

I haven't checked which ones are used but the version without _1 has a bug a line 31 https://github.com/standardcombo/LootMMO/blob/main/Data/Scripts/_LuaEvents.lua#L31 where it is iterating over a table that does not exist.

**Comment by CommanderFoo** [comment]
I've removed `_LuaEvents_1` as there was nothing referencing it.

The bug has been fixed in this commit: [https://github.com/standardcombo/LootMMO/commit/8688077904e05f9437e0afbf06302c57d5bbdafa](https://github.com/standardcombo/LootMMO/commit/8688077904e05f9437e0afbf06302c57d5bbdafa)

**Comment by CommanderFoo** [comment]
https://github.com/standardcombo/LootMMO/commit/c6ebabac2d6513327e0af11f07197275310239d5
