### ISSUE TITLE
Bug with clearing reward sets in QuestController

### ISSUE THREAD

**Issue by StanzillaManticore** [standardcombo/LootMMO#4]
In the QuestController at line 465 https://github.com/standardcombo/LootMMO/blob/development/Data/Scripts/QuestController.lua#L465 the code tries to use the index `i` which is not available there because the function is outside of the loop

**Comment by CommanderFoo** [comment]
https://github.com/standardcombo/LootMMO/commit/018ea533a7454027da7b69bc866c458c15ac4166
