### ISSUE TITLE
Bug with checking for `player` in FoodEquipmentClient

### ISSUE THREAD

**Issue by StanzillaManticore** [standardcombo/LootMMO#5]
In line 99 here https://github.com/standardcombo/LootMMO/blob/development/Data/Scripts/FoodEquipmentClient.lua#L99 the function is checking against `player` being equal to the equipment owner, but `player` was not passed to the function so this will always be nil.

**Comment by CommanderFoo** [comment]
https://github.com/standardcombo/LootMMO/commit/846df3fd260b525cf687225afb24de4e4f71cd60
