### ISSUE TITLE
Bug in OnPressPlayEffects

### ISSUE THREAD

**Issue by StanzillaManticore** [standardcombo/LootMMO#7]
On line 42 here https://github.com/standardcombo/LootMMO/blob/main/Data/Scripts/OnPressPlayEffects.lua#L42 the function tries to iterate over `effects` which is nil, `_effects` was used before so could be a typo.

**Comment by CommanderFoo** [comment]
https://github.com/standardcombo/LootMMO/commit/54486a09f5145f73d14fd15590030fb5351dd7e6
