### ISSUE TITLE
Bug in EagleMobController

### ISSUE THREAD

**Issue by StanzillaManticore** [standardcombo/LootMMO#8]
In the `Setup()` function there is a check against `OwnerID` which does not exist https://github.com/standardcombo/LootMMO/blob/main/Data/Scripts/EagleMobController.lua#L19

**Comment by CommanderFoo** [comment]
Fixed in development branch by luapi.

https://github.com/standardcombo/LootMMO/blob/b11a33479f7620b0b35ab4d1af86a8562d113143/Data/Scripts/EagleMobController.lua#L19
